<a href="https://colab.research.google.com/github/Ratnasari124/Mechine_Learning_Ratnasari/blob/main/Ratnasari_22417200007_Mesin_Learning_JS%20_1_Ekstrasi_Fitur.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Nama : Ratnasari  

Kelas : TI 3D

Absen : 25  

NIM : 2241720007  



**Praktikum BAB 1. Ekstraksi Fitur**

1. Implementasi Normaslisasi

In [ ]:
def norm_data(data):
  data_max = max(data)
  data_min = min(data)
  data_len = len(data)

  for i in range(0, data_len):
    data[i] = (data[i] - data_min) / (data_max - data_min)

  return data

# Contoh Penggunaan
data = [10, 11, 12, 14, 16]
n_data = norm_data(data) #melakukan normalisasi
print(n_data)

[0.0, 0.16666666666666666, 0.3333333333333333, 0.6666666666666666, 1.0]


In [ ]:
#ini pake library meskipun gak pake rumus bisa menghasilkan hitungan

import numpy as np
from sklearn.preprocessing import MinMaxScaler

np.set_printoptions(precision=6) #bulatkan 4 angka dibelakng koma
np.set_printoptions(suppress=True) #hilangkan nilai e

#kita akan membentuk data
#hal ini dikarenakan, scikit-learn hanya menerima input
#dalam bentuk n-dimensional array
data = [
    [100, 0.0001],
    [50, 0.05],
    [30, 0.003]
]

#Ubah ke bentuk numpy n-dimensional array
data = np.asarray(data)
print('Data Asli')
print(data)

#Mendefinisikan obye MinMaxScaler
scaler = MinMaxScaler()
#transformasidata
scaled = scaler.fit_transform(data)
print('Data Normalisasi')
print(scaled)

Data Asli
[[100.       0.0001]
 [ 50.       0.05  ]
 [ 30.       0.003 ]]
Data Normalisasi
[[1.       0.      ]
 [0.285714 1.      ]
 [0.       0.058116]]


2. Imlementasi Standarisasi

In [ ]:
import numpy as np
from sklearn.preprocessing import StandardScaler

np.set_printoptions(precision=6) #bulatkan 4 angka dibelakng koma
np.set_printoptions(suppress=True) #hilangkan nilai e

#kita akan membentuk data
#hal ini dikarenakan, scikit-learn hanya menerima input
#dalam bentuk n-dimensional array
data = [
    [100, 0.0001],
    [50, 0.05],
    [30, 0.003]
]

#Ubah ke bentuk numpy n-dimensional array
data = np.asarray(data)
print('Data Asli')
print(data)

#Mendefinisikan obye MinMaxScaler
scaler = StandardScaler()
#transformasi data
scaled = scaler.fit_transform(data)
print('Data Standarisasi')
print(scaled)


Data Asli
[[100.       0.0001]
 [ 50.       0.05  ]
 [ 30.       0.003 ]]
Data Standarisasi
[[ 1.358732 -0.76956 ]
 [-0.339683  1.412317]
 [-1.019049 -0.642757]]


3. Implementasi Ordinal Encoding

In [ ]:
#pengurutan berdasarkan huruf

from sklearn.preprocessing import OrdinalEncoder

#inisial obyek Ordinal Encoder
oe = OrdinalEncoder()

#Definisikan data
#dalam bentuk 2d
data=[
    ['Politeknik Negeri Malang'],
    ['Politeknik Elektronika Negeri Surabaya'],
    ['Politeknik Negeri Jakarta'],
    ['Politeknik Negeri Semarang']
]

#Transformasi Ordinal Encoder
transform_oe = oe.fit_transform(data)

print('Data Asli')
print(data)

print('Data Transformasi Ordinal Encoder')
print(transform_oe)

Data Asli
[['Politeknik Negeri Malang'], ['Politeknik Elektronika Negeri Surabaya'], ['Politeknik Negeri Jakarta'], ['Politeknik Negeri Semarang']]
Data Transformasi Ordinal Encoder
[[2.]
 [0.]
 [1.]
 [3.]]


4. Implementasi One Hot Encoding

In [ ]:
#menggunakan binner, jadi awalnya sama kayak di ordinal encoder yakni di urutkan dulu setelah itu perhitungan nya di jadiin binner misal 2 jadi 0010

from sklearn.preprocessing import OneHotEncoder

#inisial obyek Ordinal Encoder
ohe = OneHotEncoder()

#Definisikan data
#dalam bentuk 2d
data=[
    ['Politeknik Negeri Malang'],
    ['Politeknik Elektronika Negeri Surabaya'],
    ['Politeknik Negeri Jakarta'],
    ['Politeknik Negeri Semarang']
]

#Transformasi Ordinal Encoder
transform_ohe = ohe.fit_transform(data)

print('Data Asli')
print(data)

print('Data Transformasi One-Hot Encoder')
print(transform_ohe.toarray())

Data Asli
[['Politeknik Negeri Malang'], ['Politeknik Elektronika Negeri Surabaya'], ['Politeknik Negeri Jakarta'], ['Politeknik Negeri Semarang']]
Data Transformasi One-Hot Encoder
[[0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]]


5. Implementasi Dummy Variable Encoding

In [ ]:


from sklearn.preprocessing import OneHotEncoder

#inisial obyek Ordinal Encoder
de = OneHotEncoder(drop='first')

#Definisikan data
#dalam bentuk 2d
data=[
    ['Politeknik Negeri Malang'],
    ['Politeknik Elektronika Negeri Surabaya'],
    ['Politeknik Negeri Jakarta'],

    ['Politeknik Negeri Semarang']
]

#Transformasi Ordinal Encoder
transform_de = ohe.fit_transform(data)

print('Data Asli')
print(data)

print('Data Transformasi One-Hot Encoding')
print(transform_ohe.toarray())

Data Asli
[['Politeknik Negeri Malang'], ['Politeknik Elektronika Negeri Surabaya'], ['Politeknik Negeri Jakarta'], ['Politeknik Negeri Semarang']]
Data Transformasi One-Hot Encoding
[[0. 0. 1. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]]


6. Studi Kasus Ekstrasi

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

corpus = [
    'the house had a tiny little mouse',
    'the cat saw the mouse',
    'the mouse ran away from the house',
    'the cat finally ate the mouse',
    'the end of the mouse story'
]

#Inisialisasi obyek TFidfVectorizer
vect = TfidfVectorizer(stop_words='english')

#Pembobotan TF-IDF
resp = vect.fit_transform(corpus)

#cetak hasil
print('\n\nHasil TP-IDF\n')
print(resp)

#cetak hasil per array
print('\n\nHasil Perhitungan Untuk per Array\n')
print(resp.toarray())

#Cetak Hasil
print('\n\nHasil Token\n')
print(vect.get_feature_names_out())



Hasil TP-IDF

  (0, 7)	0.2808823162882302
  (0, 6)	0.5894630806320427
  (0, 11)	0.5894630806320427
  (0, 5)	0.47557510189256375
  (1, 9)	0.7297183669435993
  (1, 2)	0.5887321837696324
  (1, 7)	0.3477147117091919
  (2, 1)	0.5894630806320427
  (2, 8)	0.5894630806320427
  (2, 7)	0.2808823162882302
  (2, 5)	0.47557510189256375
  (3, 0)	0.5894630806320427
  (3, 4)	0.5894630806320427
  (3, 2)	0.47557510189256375
  (3, 7)	0.2808823162882302
  (4, 10)	0.6700917930430479
  (4, 3)	0.6700917930430479
  (4, 7)	0.3193023297639811


Hasil Perhitungan Untuk per Array

[[0.       0.       0.       0.       0.       0.475575 0.589463 0.280882
  0.       0.       0.       0.589463]
 [0.       0.       0.588732 0.       0.       0.       0.       0.347715
  0.       0.729718 0.       0.      ]
 [0.       0.589463 0.       0.       0.       0.475575 0.       0.280882
  0.589463 0.       0.       0.      ]
 [0.589463 0.       0.475575 0.       0.589463 0.       0.       0.280882
  0.       0.       0.   

**PRAKTIKUM**

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Baca data dari file 'corpus.txt'
with open('corpus.txt', 'r') as file:
    corpus = file.readlines()

# Inisialisasi objek TFidfVectorizer
vect = TfidfVectorizer(stop_words='english')

# Pembobotan TF-IDF
resp = vect.fit_transform(corpus)

# Cetak hasil TF-IDF
print('\n\nHasil TF-IDF\n')
print(resp)

# Cetak hasil per array
print('\n\nHasil Perhitungan Untuk per Array\n')
print(resp.toarray())

# Cetak hasil token
print('\n\nHasil Token\n')
print(vect.get_feature_names_out())




Hasil TF-IDF

  (0, 3)	1.0
  (1, 8)	0.31257907911644855
  (1, 7)	0.579262311604141
  (1, 12)	0.579262311604141
  (1, 6)	0.48083746527154797
  (2, 10)	0.7106281860049563
  (2, 2)	0.5898824226331707
  (2, 8)	0.3834661767662525
  (3, 1)	0.579262311604141
  (3, 9)	0.579262311604141
  (3, 8)	0.31257907911644855
  (3, 6)	0.48083746527154797
  (4, 0)	0.579262311604141
  (4, 5)	0.579262311604141
  (4, 2)	0.48083746527154797
  (4, 8)	0.31257907911644855
  (5, 11)	0.6606476647333884
  (5, 4)	0.6606476647333884
  (5, 8)	0.3564958992255601


Hasil Perhitungan Untuk per Array

[[0.       0.       0.       1.       0.       0.       0.       0.
  0.       0.       0.       0.       0.      ]
 [0.       0.       0.       0.       0.       0.       0.480837 0.579262
  0.312579 0.       0.       0.       0.579262]
 [0.       0.       0.589882 0.       0.       0.       0.       0.
  0.383466 0.       0.710628 0.       0.      ]
 [0.       0.579262 0.       0.       0.       0.       0.480837 0.
  0.3